os: windows
language: bash
env:
  global:
    - au_version=
    - au_push=true
    - au_test_groups=1
    - github_user_repo=$TRAVIS_REPO_SLUG
    - mail_user=YOUR_EMAIL_ACCOUNT_HERE_ENCRYPTED_STRING
    - mail_pass=YOUR_EMAIL_PASSWORD_HERE_ENCRYPTED_STRING
    - mail_server=smtp.gmail.com
    - mail_port=587
    - mail_enablessl=true
before_install:
- git config --global user.email "chocolatey@realdimensions.net"
- git config --global user.name "Chocolatey"
- git config --global core.safecrlf false
- powershell Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine
install:
- powershell '. ./init.ps1; AUPackages-Install'
script:
- powershell '. ./init.ps1; AUPackages-BuildScript'
